language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

jobs:
  include:
    - stage: test
      script: ls
    - # stage name not required, will continue to use `test`
      script: ls
    - stage: deploy
      script: ls
